[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "GFw24Sd3CGJRkYGE8mbmNDrUigzqfBDsfDEHpakgdoFm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/artemshalamov/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
